# Generated by Django 4.1.3 on 2022-11-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_endorsement_message_question_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='FeedBack',
        ),
    ]
