# Generated by Django 4.1.3 on 2022-11-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_skill_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='body',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='title',
            new_name='name',
        ),
    ]
