# Generated by Django 4.1.3 on 2022-11-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_body_feedback_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='logo',
        ),
    ]
