# Generated by Django 4.1.3 on 2022-11-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_project_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endorsement',
        ),
    ]
